repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.27.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.25.0
    hooks:
      - id: commitizen

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        stages: [pre-push]
      - id: clippy
        stages: [pre-push]
        args: [
            "--all-targets",
            # "--all-features",
            "--workspace",
            "--",
            "-D",
            "warnings",
          ]
