[package]
name = "sfsu"
description = "Stupid Fast Scoop Utils"
version = "1.8.1"
edition = "2021"

[workspace]
members = ["sfsu-derive"]

[[bench]]
name = "searching"
harness = false

[profile.release]
codegen-units = 1
lto = true

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = [
    "serde",
    "clock",
    "std",
], default-features = false }
clap = { version = "4.4", features = ["derive"] }
colored = "2.1"
const-str = { version = "0.5", features = ["all"] }
derive_more = "0.99"
directories = "5.0"
dunce = "1.0"
git2 = "0.18"
human-panic = "1.2"
indicatif = { version = "0.17", features = ["rayon", "tokio"] }
itertools = "0.12"
quork = "0.6"
rayon = "1.8"
regex = "1.10"
reqwest = { version = "0.11", features = ["blocking", "stream"] }
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
sfsu-derive = { path = "./sfsu-derive" }
shadow-rs = "0.26"
strum = { version = "0.25", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.35.1", features = ["full"] }
url = { version = "2.5", features = ["serde"] }
# This is a temporary solution to a resolution error with reqwest
futures-util = "=0.3.29"
futures-core = "0.3.30"
bytes = "1.5.0"
tokio-stream = "0.1.14"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[build-dependencies]
shadow-rs = "0.26"
