[package]
name = "sfsu"
description = "Stupid Fast Scoop Utils"
version = "1.4.10"
edition = "2021"

[workspace]
members = ["sfsu-derive"]

[profile.release]
codegen-units = 1

[dependencies]
anyhow = "1.0.75"
chrono = { version = "0.4.26", features = ["serde", "clock", "std"], default-features = false }
clap = { version = "4.3.24", features = ["derive"] }
colored = "2.0.4"
derive_more = "0.99.17"
dirs = "5.0.1"
dunce = "1.0.4"
itertools = "0.11.0"
paste = "1.0.14"
quork = "0.4.0"
rayon = "1.7.0"
regex = "1.9.3"
serde = { version = "1.0.186", features = ["derive"] }
serde_json = "1.0.105"
sfsu-derive = { path = "./sfsu-derive" }
strum = { version = "0.25.0", features = ["derive"] }
