[package]
name = "sfst"
description = "Stupid Fast Scoop Tools"
version = "1.1.5"
edition = "2021"

[[bin]]
name = "sfss"
path = "src/bin/search.rs"

[[bin]]
name = "sfsl"
path = "src/bin/list.rs"

[[bin]]
name = "sfst-hook"
path = "src/bin/hook.rs"

[profile.release]
strip = true
codegen-units = 1

[dependencies]
anyhow = "1.0.66"
chrono = { version = "0.4.23", features = ["serde", "clock", "std"], default-features = false }
clap = { version = "4.0.29", features = ["derive"] }
dirs = "4.0.0"
dunce = "1.0.3"
git2 = "0.15.0"
rayon = "1.6.1"
regex = "1.7.0"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.89"
which = "4.3.0"
