[package]
name = "sfsu"
description = "Stupid Fast Scoop Utils"
version = "1.2.1"
edition = "2021"

[profile.release]
# strip = true
codegen-units = 1

[dependencies]
anyhow = "1.0.68"
chrono = { version = "0.4.23", features = ["serde", "clock", "std"], default-features = false }
clap = { version = "4.1.1", features = ["derive"] }
dirs = "4.0.0"
dunce = "1.0.3"
rayon = "1.6.1"
regex = "1.7.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
which = "4.3.0"
