[package]
name = "sfsu"
description = "Stupid Fast Scoop Utils"
version = "1.4.6"
edition = "2021"

[workspace]
members = ["sfsu-derive"]

[profile.release]
codegen-units = 1

[dependencies]
anyhow = "1.0.70"
chrono = { version = "0.4.23", features = ["serde", "clock", "std"], default-features = false }
clap = { version = "4.1.13", features = ["derive"] }
colored = "2.0.0"
dirs = "4.0.0"
dunce = "1.0.3"
itertools = "0.10.5"
paste = "1.0.12"
rayon = "1.7.0"
regex = "1.7.3"
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
sfsu-derive = { path = "./sfsu-derive" }
strum = { version = "0.24.1", features = ["derive"] }
