[package]
name = "sfsu"
description = "Stupid Fast Scoop Utils"
version = "1.1.2"
edition = "2021"

[lib]
name = "sfst"
path = "src/lib.rs"

[[bin]]
name = "sfss"
path = "src/bin/search.rs"

[[bin]]
name = "sfsl"
path = "src/bin/list.rs"

[[bin]]
name = "sfst-hook"
path = "src/bin/hook.rs"

[profile.release]
strip = true
codegen-units = 1

[dependencies]
anyhow = "1.0.66"
chrono = { version = "0.4.22", features = ["serde"] }
clap = { version = "4.0.18", features = ["derive"] }
dirs = "4.0.0"
dunce = "1.0.3"
git2 = "0.15.0"
human-panic = "1.0.3"
rayon = "1.5.3"
regex = "1.6.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
thiserror = "1.0.37"
which = "4.3.0"
