[package]
description = "Stupid Fast Scoop Utils"
edition = "2021"
license = { workspace = true }
name = "sfsu"
publish.workspace = true
version.workspace = true

[workspace]
members = ["crates/*"]
package.license = "Apache-2.0"
package.publish = false
package.version = "1.11.0-beta.5"

[workspace.dependencies]
chrono = { version = ">=0.4.38", features = [
    "clock",
    "serde",
    "std",
], default-features = false }
console = { version = "0.15.8", features = ["windows-console-colors"] }
futures = "0.3"
git2 = "0.18"
indicatif = { version = "0.17", features = [
    "improved_unicode",
    "rayon",
    "tokio",
] }
itertools = "0.12"
log = { version = "0.4", features = ["std"] }
owo-colors = { version = "4.0", features = ["supports-colors"] }
quork = "0.6"
rayon = "1.10"
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }

[[bench]]
harness = false
name = "searching"

[[bench]]
harness = false
name = "ref-matching"

[[bench]]
harness = false
name = "serde"

[[bench]]
harness = false
name = "autoupdate"

[profile.release]
codegen-units = 1
lto = true

[profile.profiling]
inherits = "dev"
opt-level = 3

[features]
beta = ["download", "sprinkles/beta"]
default = []
download = ["sprinkles/manifest-hashes"]
# Breaking changes are locked behind this feature flag
v2 = ["sprinkles/v2"]

[dependencies]
anyhow = "1.0.82"
bat = "0.24"
clap = { version = "4.5.4", features = [
    "derive",
    "env",
    "string",
    "unicode",
    "wrap_help",
] }
console.workspace = true
futures.workspace = true
git2.workspace = true
human-panic = "2.0"
indicatif.workspace = true
itertools.workspace = true
log = { workspace = true }
open = "5.1"
owo-colors.workspace = true
parking_lot = "0.12"
quork.workspace = true
rayon.workspace = true
regex.workspace = true
serde.workspace = true
serde_json = { version = "1.0", features = ["preserve_order"] }
sfsu-derive = { path = "./crates/derive" }
shadow-rs = "0.27"
sprinkles = { version = "1.11.0-beta.4", path = "crates/sprinkles" }
tokio = { version = "1.37", features = ["full"] }

[dev-dependencies]
chrono.workspace = true
criterion = { version = "0.5", features = ["async_tokio", "html_reports"] }
git2 = { workspace = true }

[build-dependencies]
git2.workspace = true
shadow-rs = "0.27"
winres = "0.1"
