[package]
name = "sfsu"
description = "Stupid Fast Scoop Utils"
version = "1.4.0"
edition = "2021"

[workspace]
members = ["sfsu-derive"]

[profile.release]
# strip = true
codegen-units = 1

[dependencies]
anyhow = "1.0.68"
chrono = { version = "0.4.23", features = ["serde", "clock", "std"], default-features = false }
clap = { version = "4.1.4", features = ["derive"] }
derive_more = "0.99.17"
dirs = "4.0.0"
dunce = "1.0.3"
paste = "1.0.11"
rayon = "1.6.1"
regex = "1.7.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
strum = { version = "0.24.1", features = ["derive"] }
sfsu-derive = { path = "./sfsu-derive" }
