[package]
name = "sfsu"
description = "Stupid Fast Scoop Utils"
version = "1.4.8"
edition = "2021"

[workspace]
members = ["sfsu-derive"]

[profile.release]
codegen-units = 1

[dependencies]
anyhow = "1.0.71"
chrono = { version = "0.4.26", features = ["serde", "clock", "std"], default-features = false }
clap = { version = "4.3.3", features = ["derive"] }
colored = "2.0.0"
derive_more = "0.99.17"
dirs = "5.0.1"
dunce = "1.0.4"
itertools = "0.10.5"
paste = "1.0.12"
quork = "0.3.2"
rayon = "1.7.0"
regex = "1.8.4"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
sfsu-derive = { path = "./sfsu-derive" }
strum = { version = "0.24.1", features = ["derive"] }
