# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json

name: Bug Report
description: Create a report to help us improve
title: "<COMMAND:> Brief issue description"
labels: [bug]
assignees: jewlexx

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug!
        Please make sure you have read the [FAQs](https://github.com/winpax/FAQs), before you report an issue.

        If you have a question, please ask it on [the discussions page](https://github.com/winpax/sfsu/discussions).

        If you have a bug report, feature request, or other issue, then [open an issue](https://github.com/winpax/sfsu/issues/new/choose).

  - type: textarea
    id: version
    attributes:
      label: Version
      description: Provide the output of `sfsu --version`
    validations:
      required: true

  - type: input
    id: error-report
    attributes:
      label: Error Report
      description: Please provide a pastebin link to the error report.
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: Description
      description: Briefly describe the bug. This should be 1-2 sentences, and give a general overview of the issue.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide a list of steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
