# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json

blank_issues_enabled: false
contact_links:
  - name: FAQs
    url: https://github.com/winpax/FAQs
    about: Please check the FAQs before you report an issue.
  - name: Discussions
    url: https://github.com/winpax/sprinkles/discussions
    about: Please ask questions on the discussions page.
