[package]
name = "instant"
version = "0.1.0"
edition = "2021"
authors.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
rightnow = "0.1.0"
web-time = "1.1.0"
